theme: jekyll-theme-minimal
title: Guowei Zhang
logo: /files/img/me.jpg
description: I am a researcher in computer architecture. My broader interests include computer systems and digital circuits.
google_analytics: UA-73202302-2
